services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5555:5678"
    volumes:
      - /Users/rociobenitezgarcia/Documents/projects/n8n/volume:/home/node/.n8n
    environment:
      - N8N_COMMUNITY_PACKAGE_ALLOW_TOOL_USE=true
      - N8N_EDITOR_BASE_URL=https://fully-bold-kid.ngrok-free.app
      - WEBHOOK_URL=https://fully-bold-kid.ngrok-free.app
      - WEBHOOK_TUNNEL_URL=https://fully-bold-kid.ngrok-free.app
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
